### ISSUE TITLE
[FEATURE REQUEST] Wallpaper Support on SB Touch

### ISSUE THREAD

**Issue by rumich** [AF-1/jivelite-darkflatskin#1]
Thanks for the great applet / skin and all the packaging / documentation around it! This is just what I was looking for since the old way of copying over stuff for the ratings display wasn't fully compatible to my current versions on the Touch client any more. Feels like xmas in October :)

## DESCRIBE THE FEATURE

It would be great if the skin supported wallpapers on SB Touch just like the default skins. Is this feasible? I'm happy to test since I know you do not own a Touch yourself.

**Comment by AF-1** [comment]
Thanks. If you mean different wallpapers as *background* for the `NowPlaying screen`, then no, sorry. Using the black background was a deliberate choice. I've tested other wallpapers and it was difficult to see the dimmed audio metadata text or the status icons or rating stars. I know it would probably look nice and fancy but readability/visibility of the important information was my priority here. I think there was another problem (I forget) that made me hard-code the black background.

Anyway, if you want more/different wallpapers for the *browse menus*, you can just copy them to the user folder on your SBT, which I think is:

`/etc/squeezeplay/userpath/wallpapers/`

If you have problems logging in or copying stuff to your SBT, [**this**](https://github.com/AF-1/sobras/wiki/Command-line-access-to-SB-Radio-and-SB-Touch) may help.
