### ISSUE TITLE
Homescreen from Grid Skin

### ISSUE THREAD

**Issue by KiwiKing3** [AF-1/jivelite-darkflatskin#3]
Is there any way to use the Homescreen from the Grid Skin?
I really like your Skin! It makes Jivelite soo much more modern, but I really like the Grid Homescreen with those big icons from the Grid Skin. Is there any way to "merge" these skins, so that I can have the Homescreen from the Grid Skin and everything else from your skin?

Thanks! 

BTW, I'm using PiCorePlayer with a 5" 800x480 Touchscreen.

**Comment by AF-1** [comment]
I'll check if I can include this in the next update for pCP (800x480 only). Can't say _when_ this is going to happen though.

**Comment by AF-1** [comment]
Please uninstall this applet. Then install v1.0.**7**. It has a grid skin option for pCP (800x480). Not perfect but the best I could do.

**Comment by KiwiKing3** [comment]
Wow, thanks! It looks really good, thanks for your effort.![PXL_20240210_170642374.jpg](https://github.com/AF-1/jivelite-darkflatskin/assets/102294130/b3ebae4e-a3e5-4fb3-a5b7-d56ac5499945)

**Comment by AF-1** [comment]
Your screenshot does not show the _Dark Flat *Grid* Skin_, does it? The 2 icons top left and top right should be “flat“ like in the last screenshot [here](https://github.com/AF-1/jivelite-darkflatskin#screenshots). This looks more like the default PiGridSkin.

**Comment by KiwiKing3** [comment]
Oh, looks like it got changed back. Here's the right photo. 

![PXL_20240211_083003048.MP.jpg](https://github.com/AF-1/jivelite-darkflatskin/assets/102294130/1a09134d-75c9-4d81-b292-6b4987245e7b)
