### ISSUE TITLE
[ISSUE] raspberry and slimserver

### ISSUE THREAD

**Issue by Markolino1972** [AF-1/jivelite-darkflatskin#4]
## Checklist

❗️ **Please take a quick look at [**this checklist**](https://github.com/AF-1/sobras/wiki/Checklist-to-eliminate-common-causes-of-LMS-(plugin)-problems) to eliminate common causes of LMS (plugin) problems. Thank you.**
<br><br><br>

---

## DESCRIBE THE BUG

FUCK YOU WITH YOUR RASPBERRY?S
first you killed mysqueezebox.com with your bad sounding stupid rapberry's boards
squeezebox touch is miles ahead musically speaking from a raspberry

YOU ARE ALL A BENCH OF IDIOTS INSTEAD OF IMPROVING slimserver YOU ARE ALWAYS ADDING MORE BUGS that impacts sound quality on both sides server and clients

FUCK YOU ALL RETARDED IDIOTS

<br><br>
## TO REPRODUCE

<br><br>
## EXPECTED BEHAVIOR

<br><br>
## LOG EXCERPT
* Add relevant (error) messages from the **LMS server log** (file path at the bottom of *LMS settings* > *Information*). Use the **time stamps** in the log to find messages created around the time your problem occurred.
* If there are no server log error messages, set the **debug level for this plugin** to **info** in *LMS settings* > *Advanced* > *Logging*, **reproduce the problem** and **check the server log** again. If there's still nothing, **repeat** this step with the debug level set to **debug**.
* Alternatively, *upload the complete LMS server log file somewhere* (see UPLOADS below) and don't forget to *add the time stamp of when the problem occurred*.

<br><br>
## VERSION INFO
* LMS version:
* OS (version):
* Plugin version:
* Web skin/controller:     Examples: LMS Default, Material, jivelite (= piCorePlayer, SqueezePlay, Touch, Radio)
* Browser (version):

If the problem occurs with a specific web skin/controller (e.g. Material), please check whether it also occurs when using other web skins/controllers (e.g. LMS default skin).

<br><br>
## SCREENSHOTS

<br><br>
## ADDITIONAL CONTEXT

<br><br>
## UPLOADS
In case you want to provide larger files to illustrate the problem (e.g. your library.db, persist.db or LMS server log file), please use a service like **https://wetransfer.com/** and **include the download link in your bug report**.
<br>

You can delete the checklist and other parts from your issue report that don't apply to your problem.

**Comment by Markolino1972** [comment]
i use fw7.5.0 on my SBT everything works beautifully even as a home music server
sound quality is so natural

what the fuck are you doing stupid fired logitech retarded employess

**Comment by AF-1** [comment]
Don't be stupid.
